Created and updated migration and seed file for extra backend filter …
Lambda-School-Labs/Express_Groomer-TeamC-BE pull request #25
Opened 2021-01-07 00:58 UTC by SRattacasa

…options

2021-01-07 00:58 UTC, SRattacasa commented
- Changing directory to the /config path, I created a new database migration to add a "dogs" and "cats" boolean field to the groomers database table
- This is to be used for filtering out groomers in the search component based on the animals serviced

2021-01-07 01:44 UTC, SRattacasa commented
- Had to do some troubleshooting of the npm lint script to include the --fix flag 

The automated testing was failing on some eslint errors, so I added the --fix flag and it seems to have resolved them. It's passing the tests now.

2021-01-13 01:25 UTC, coryortega commented on data/migrations/20210106195157_add_animals_to_groomers.js
> +    });
check what it defaults to maybe '.default()'

2021-01-15 01:13 UTC, SRattacasa commented
- Ran against development database
- Verified the column created successfully
- Validated the seed file ran and created the desired values

2021-01-15 02:18 UTC, coryortega requested changes
Looks good! Just change the defaultTo to be on the exports.up function

2021-01-15 02:18 UTC, coryortega commented on data/migrations/20210106195157_add_animals_to_groomers.js
> +      table.dropColumn('cats').defaultTo(false);
.defaultTo should be on the exports.up

2021-01-15 02:18 UTC, coryortega commented on data/migrations/20210106195157_add_animals_to_groomers.js
> +        table.boolean('cats')
add the .defaultTo up here

2021-01-15 02:41 UTC, coryortega requested changes

2021-01-15 02:41 UTC, coryortega commented on data/migrations/20210106195157_add_animals_to_groomers.js
> +      table.dropColumn('cats').defaultTo(false);
Get rid of the .defaultTo on the down

2021-01-20 00:32 UTC, coryortega approved these changes

2021-01-20 00:33 UTC, AustinKelsay approved these changes

2021-01-20 01:17 UTC, merged